name: Post-commit Validation

on:
  - pull_request

env:
  NIGHTLY_VERSION: nightly-2025-08-10

defaults:
  run:
    shell: bash

jobs:
  validation:
    name: Build & Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.rustup/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ env.NIGHTLY_VERSION }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install --profile minimal --component rust-src,rustfmt,clippy,miri $NIGHTLY_VERSION
          cargo install cargo-sort

      - name: Configure Environment
        run: rustup default $NIGHTLY_VERSION

      - name: Check Formatting
        run: cargo fmt --check

      - name: Check Dependency Ordering
        run: cargo sort --workspace --grouped --check

      - name: Check Static Analyzer
        run: cargo clippy -- -D warnings

      - name: Run Miri
        run: cargo miri test
